apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: todos-svc
  namespace: todos
  labels:
    app.kubernetes.io/name: todos-svc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: todos-svc
  replicas: 3
  template:
    metadata:
      name: todos-svc
      namespace: todos
      labels:
        app.kubernetes.io/name: todos-svc
    spec:
      containers:
        - name: todos-svc
          image: todos/todos-svc
          imagePullPolicy: Never
