apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: graphql-svc
  namespace: todos
  labels:
    app.kubernetes.io/name: graphql-svc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graphql-svc
  replicas: 3
  template:
    metadata:
      name: graphql-svc
      namespace: todos
      labels:
        app.kubernetes.io/name: graphql-svc
    spec:
      containers:
        - name: graphql-svc
          image: todos/graphql-svc:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-svc
  namespace: todos
  labels:
    app.kubernetes.io/name: graphql-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: graphql-svc
  ports:
    - port: 8080
      nodePort: 30100
